# This is a basic workflow to help you get started with Actions

name: W&B

# Controls when the workflow will run
on: issue_comment
permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  MAGIC_COMMENT: "/wandb" # this is a parameter you can change
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  see-comments:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        # Print payload for debug purposes 
      - name: see payload DEBUG
        run: echo "PAYLOAD:\n${PAYLOAD}\n"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
          

      - name: filter for magic comment
        id: filter
        if: contains(github.event.comment.body, env.MAGIC_COMMENT) 
        run: echo "magic commment detected"
        
      - name: parse magic comment
        if: steps.filter.outcome == 'success'
        id: get-magic-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search('${{ env.MAGIC_COMMENT }}[\s+](\S+)', comment)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            if match:
              print(f'VAL_FOUND=true', file=f)
              print(f'MAGIC_VAL={match.group(1)}', file=f)
            else:
              print(f'VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: print value of magic command
        if:  steps.get-magic-value.outcome == 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
        run: echo "the value is ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"

      - name: generate comparison report 
        if: steps.get-magic-value.outcome == 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
        id: wandb-report
        run: python .github/workflows/compare_runs.py
        env:
            WANDB_ENTITY: andrea-faviait
            WANDB_PROJECT: swiss-delay-prediction
            RUN_ID: "${{ steps.get-magic-value.outputs.MAGIC_VAL }}"
            BASELINE_TAGE: baseline
            WANDB_API_KEY: "${{ secrets.WANDB_API_KEY }}"
  
      - name: Make a comment with the GitHub API
        uses: actions/github-script@v6
        if: steps.wandb-report.outcome == 'success'
        with:
          script: |
             var msg = `👋 Hello!  Here's the comparison between baseline and new run id: \`${process.env.MAGIC_VAL}\ \n
             Report available here: `$REPORT_URL` `

             github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              body: msg
              })  
        env:
          MAGIC_VAL: "${{ steps.get-magic-value.outputs.MAGIC_VAL }}"
          REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
